# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'Inventories'},
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='type',
            new_name='itemType',
        ),
    ]
