# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20160604_1839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemtype',
            options={'verbose_name_plural': 'Item Types'},
        ),
        migrations.AddField(
            model_name='inventory',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
